/**
 * ALLOWS FOR A USER TO SWAP BETWEEN THE COVER WEBPAGE AND PLATFORM
 */
function client(){

}

/**
 * ALLOWS FOR A USER TO CREATE A NEW DATA INSTANCE (FORM WITH DATA)
 */
function data(){}

/**
 * ALLOWS A USER TO CREATE A NEW FORM TEMPLATE
 */
function form(){}

/**
 * ALLOWS A USER TO ACCESS DATA SAVED ON A SYNC SERVER
 */
function access(){}

/**
 * ALLOWS A USER TO ACCESS THE HELP FUNCTIONS
 */
function help(){}

/**
 * ALLOWS A USER TO LINK EXTERNAL DATA
 */
function link(){}

/**
 * ALLOWS A USER TO GRANT ACCESS TO ANOTHER USER ON THE SAME SYNC SERVER
 */
function share(){}

/**
 * ALLOWS A USER TO VIEW THE LICENSE INFORMATION FOR THE DATA
 */
function license(){}